# Task 2C: Evaluation and baseline comparison
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/krishanSKDA/CDAZZDEV-MLE-Krishan_Danushka/blob/main/task2_genai/Task2_Eval.ipynb)

Base model (same system prompt, no fine-tuning) vs merged fine-tuned model on the **identical** held-out test set, greedy decoding for both. Needs a T4 GPU and `GEMINI_API_KEY` (LLM judge: `gemini-3.1-flash-lite`).

In [1]:
import os, sys, subprocess

REPO_URL = "https://github.com/krishanSKDA/CDAZZDEV-MLE-Krishan_Danushka.git"
IN_COLAB = "google.colab" in sys.modules
if IN_COLAB:
    if not os.path.exists("/content/repo"):
        subprocess.run(["git", "clone", "--depth", "1", REPO_URL, "/content/repo"], check=True)
    os.chdir("/content/repo")
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-r", "requirements.txt"], check=True)
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-r", "task2_genai/requirements-train.txt"], check=True)
else:
    while not os.path.exists("requirements.txt"):
        os.chdir("..")
sys.path.insert(0, os.getcwd())
print("repo root:", os.getcwd(), "| colab:", IN_COLAB)

repo root: /content/repo | colab: True

In [2]:
# Colab ships torchao 0.10, which recent peft/transformers reject; this project does not use torchao
!pip uninstall -y -q torchao

In [3]:
import gc, json, torch, pandas as pd
from task2_genai.dataset import DATA_DIR, load_jsonl
from task2_genai.finetune import TrainConfig, free_gpu
from task2_genai.evaluation import generate, load_for_inference, prompt_messages

BASE_ID = TrainConfig().base_model
from common.config import get_secret
from huggingface_hub import HfApi
FT_ID = f"{HfApi(token=get_secret('HF_TOKEN')).whoami()['name']}/qwen2.5-3b-risk-extractor"  # pushed by the fine-tune notebook
test = load_jsonl(DATA_DIR / "test.jsonl")
os.makedirs("task2_genai/results", exist_ok=True)
print(len(test), "test examples")

32 test examples

In [4]:
def run(model_id, name):
    model, tok = load_for_inference(model_id)
    gens = generate(model, tok, [prompt_messages(r) for r in test])
    with open(f"task2_genai/results/{name}_generations.jsonl", "w", encoding="utf-8") as f:
        for r, g in zip(test, gens):
            f.write(json.dumps({"id": r["id"], **g}, ensure_ascii=False) + "\n")
    del model
    free_gpu()
    return gens

base_gens = run(BASE_ID, "base")
ft_gens = run(FT_ID, "finetuned")

config.json:   0%|          | 0.00/661 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/35.6k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.55k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/694 [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 11.4MB

tokenizer.json: downloading bytes:           |  0.00B

chat_template.jinja:   0%|          | 0.00/2.51k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 6.17GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/243 [00:00<?, ?B/s]

## ROUGE-L and structural metrics

In [5]:
from task2_genai.evaluation import evaluate_model
base_summary, base_rows = evaluate_model("base (system prompt only)", test, base_gens)
ft_summary, ft_rows = evaluate_model("fine-tuned (QLoRA)", test, ft_gens)
comparison = pd.DataFrame([base_summary, ft_summary]).set_index("model").T
comparison["delta"] = comparison.iloc[:, 1] - comparison.iloc[:, 0]
comparison.round(4)

model                    base (system prompt only)  fine-tuned (QLoRA)   delta
rougeL_f1                                   0.6011              0.8823  0.2812
json_valid_rate                             0.1250              1.0000  0.8750
category_precision                          0.8182              0.9385  0.1203
category_recall                             0.1385              0.9385  0.8000
category_f1                                 0.2368              0.9385  0.7016
exact_category_set                          0.0312              0.9062  0.8750
quote_grounding_rate                        0.6364              0.9846  0.3483
severity_accuracy                           0.6667              0.7213  0.0546
auto_hallucination_rate                     0.0938              0.0312 -0.0625

## Additional metrics: BERTScore F1 and LLM-as-judge (structured JSON rubric)

In [6]:
from task2_genai.evaluation import bertscore_f1, gold_of
refs = [json.dumps(gold_of(r), ensure_ascii=False) for r in test]
try:
    base_rows["bertscore_f1"] = bertscore_f1([g["text"] for g in base_gens], refs)
    ft_rows["bertscore_f1"] = bertscore_f1([g["text"] for g in ft_gens], refs)
    comparison.loc["bertscore_f1"] = [base_rows["bertscore_f1"].mean(), ft_rows["bertscore_f1"].mean(),
                                      ft_rows["bertscore_f1"].mean() - base_rows["bertscore_f1"].mean()]
except Exception as exc:  # library incompatibility must not block the LLM-judge metric below
    print(f"BERTScore unavailable: {type(exc).__name__}: {exc}")
comparison.round(4)

config.json:   0%|          | 0.00/482 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.42GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaModel LOAD REPORT from: roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
pooler.dense.weight       | MISSING    |
pooler.dense.bias         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaModel LOAD REPORT from: roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
pooler.dense.weight       | MISSING    |
pooler.dense.bias         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

model                    base (system prompt only)  fine-tuned (QLoRA)   delta
rougeL_f1                                   0.6011              0.8823  0.2812
json_valid_rate                             0.1250              1.0000  0.8750
category_precision                          0.8182              0.9385  0.1203
category_recall                             0.1385              0.9385  0.8000
category_f1                                 0.2368              0.9385  0.7016
exact_category_set                          0.0312              0.9062  0.8750
quote_grounding_rate                        0.6364              0.9846  0.3483
severity_accuracy                           0.6667              0.7213  0.0546
auto_hallucination_rate                     0.0938              0.0312 -0.0625
bertscore_f1                                0.8655              0.9823  0.1168

In [7]:
from task2_genai.evaluation import judge_all, JUDGE_MODEL
print("judge:", JUDGE_MODEL)
judge_base = judge_all(test, [g["text"] for g in base_gens])
judge_ft = judge_all(test, [g["text"] for g in ft_gens])
crit = ["faithfulness", "completeness", "severity_calibration", "format_compliance"]
judge_table = pd.DataFrame({"base": judge_base[crit].mean(), "fine-tuned": judge_ft[crit].mean()})
judge_table.loc["verdict=correct"] = [(judge_base.verdict == "correct").mean(), (judge_ft.verdict == "correct").mean()]
judge_table.loc["verdict=hallucinated"] = [(judge_base.verdict == "hallucinated").mean(), (judge_ft.verdict == "hallucinated").mean()]
judge_table.round(3)

judge: gemini:gemini-3.1-flash-lite

                       base  fine-tuned
faithfulness          3.500       4.781
completeness          3.188       4.781
severity_calibration  3.781       4.281
format_compliance     3.125       5.000
verdict=correct       0.000       0.656
verdict=hallucinated  0.375       0.031

In [8]:
judge_ft.head(5)

,id,faithfulness,completeness,severity_calibration,format_compliance,verdict,rationale
0,ex_0317,5,5,5,5,correct,The candidate extraction accurately identifies...
1,ex_0243,5,5,4,5,correct,The candidate extraction is faithful to the te...
2,ex_0042,5,4,3,5,partially_correct,The candidate extraction is faithful to the te...
3,ex_0171,5,5,5,5,correct,The passage provided is a positive corporate s...
4,ex_0241,5,5,5,5,correct,The candidate extraction accurately captures t...

In [9]:
comparison.to_csv("task2_genai/results/metrics_comparison.csv")
judge_table.to_csv("task2_genai/results/judge_summary.csv")
base_rows.merge(judge_base, on="id").to_csv("task2_genai/results/base_per_sample.csv", index=False)
ft_rows.merge(judge_ft, on="id").to_csv("task2_genai/results/finetuned_per_sample.csv", index=False)

## Manual review: fine-tuned model (≥ 10 responses)
Each response below shows the passage, reference and prediction, with an *automatic* pre-check (quote grounding + category match). **Read each one yourself** and record your label (`correct`, `partially_correct`, `hallucinated`) in `MANUAL_LABELS`; the auto-label is only a hint.

In [10]:
from task2_genai.evaluation import review_sheet
N_REVIEW = len(test)
sheet = review_sheet(test, [g["text"] for g in ft_gens], ft_rows, N_REVIEW)
for _, r in sheet.iterrows():
    print("=" * 100, f"\n{r.id}  auto={r.auto_label} ({r.auto_reason})\n")
    print("PASSAGE:\n", r.passage, "\n\nREFERENCE:\n", r.gold, "\n\nPREDICTION:\n", r.prediction)

print("\nCopy into the next cell and fill each label with correct / partially_correct / hallucinated:")
print("MANUAL_LABELS = {\n" + "".join(f'    "{i}": "",\n' for i in sheet.id) + "}")

====================================================================================================
ex_0317  auto=correct (categories match, quotes grounded, severities calibrated)

PASSAGE:
 At Fenwick Holdings, our commitment to operational transparency remains paramount as we navigate an increasingly volatile digital landscape. Our primary cloud infrastructure relies heavily on specialized high-performance chipsets sourced from a single vendor, Aethelgard Silicon, which currently fulfills 92% of our server hardware requirements. Any disruption in their fabrication capacity or geopolitical trade barriers affecting their export licenses could force a total suspension of our core SaaS deployment services. While we previously encountered concerns regarding outdated legacy power cooling in our Nevada data centers, we have successfully retrofitted all facilities with state-of-the-art geothermal heat exchangers, fully neutralizing that efficiency bottleneck. Beyond operational logistics, we are proactively addressing intensifying environmental risks. Our predictive modeling suggests that a 1.5-degree Celsius rise in mean global temperatures will exacerbate climate-related volatility, specifically necessitating a 40% increase in cooling expenditures at our primary coastal hubs by 2028. Failure to adapt our physical footprint to these extreme weather patterns could significantly compress our long-term operating margins and erode the asset value of our Tier-1 data facilities. Furthermore, as regional governments introduce stricter mandates regarding scope 3 emissions, our reliance on energy-intensive third-party cloud providers may expose us to substantial carbon-tax liabilities. We are currently evaluating a pivot to carbon-neutral regional micro-centers to mitigate these evolving regulatory and physical climate threats, though the transition will require significant capital allocation over the next four fiscal years. Our audit committee continues to monitor these exposures with a focus on long-term capital preservation and infrastructure resilience.

REFERENCE:
 {
 "risks": [
  {
   "category": "supply_chain",
   "severity": "high",
   "affected_metric": "revenue",
   "evidence_quote": "Our primary cloud infrastructure relies heavily on specialized high-performance chipsets sourced from a single vendor, Aethelgard Silicon, which currently fulfills 92% of our server hardware requirements."
  },
  {
   "category": "esg_climate",
   "severity": "medium",
   "affected_metric": "operating margin",
   "evidence_quote": "Failure to adapt our physical footprint to these extreme weather patterns could significantly compress our long-term operating margins and erode the asset value of our Tier-1 data facilities."
  }
 ],
 "overall_risk_level": "high"
}

PREDICTION:
 {"risks": [{"category": "supply_chain", "severity": "high", "affected_metric": "operating margin", "evidence_quote": "Our primary cloud infrastructure relies heavily on specialized high-performance chipsets sourced from a single vendor, Aethelgard Silicon, which currently fulfills 92% of our server hardware requirements."}, {"category": "esg_climate", "severity": "medium", "affected_metric": "operating margin", "evidence_quote": "a 1.5-degree Celsius rise in mean global temperatures will exacerbate climate-related volatility, specifically necessitating a 40% increase in cooling expenditures at our primary coastal hubs by 2028."}], "overall_risk_level": "high"}
====================================================================================================
ex_0243  auto=correct (categories match, quotes grounded, severities calibrated)

PASSAGE:
 At Corvane Systems, we recognize that our long-term viability remains intrinsically linked to the shifting landscape of wireless infrastructure. Currently, we derive approximately 42% of our total annual revenue from a single telecommunications service provider based in North America, and any decision by this counterparty to reduce its capital expenditure or switch to an alternative hardware vendor could significantly diminish our future cash inflows. Furthermore, as we integrate next-generation connectivity solutions into our core platforms, we face heightened exposure to sophisticated cyber-attacks that could potentially disrupt our network operations or compromise proprietary data integrity, despite our ongoing investments in hardened security protocols. The regulatory environment also remains a complex variable in our growth strategy, as recent shifts in international spectrum allocation standards and stricter enforcement of regional antitrust laws may impose substantial compliance burdens or limit our ability to deploy critical hardware components across our key European markets. We anticipate that navigating these evolving legislative frameworks will require sustained focus and resource allocation to ensure our operational continuity. While we continue to optimize our internal processes and fortify our systems against both digital threats and compliance-related hurdles, the possibility of material disruption to our business model and financial performance cannot be fully excluded. Management remains committed to monitoring these developments closely and implementing strategic mitigations to sustain value for our stakeholders in the coming fiscal periods.

REFERENCE:
 {
 "risks": [
  {
   "category": "customer_concentration",
   "severity": "high",
   "affected_metric": "revenue",
   "evidence_quote": "we derive approximately 42% of our total annual revenue from a single telecommunications service provider based in North America, and any decision by this counterparty to reduce its capital expenditure or switch to an alternative hardware vendor could significantly diminish our future cash inflows."
  },
  {
   "category": "cybersecurity_operational",
   "severity": "medium",
   "affected_metric": "operating margin",
   "evidence_quote": "we face heightened exposure to sophisticated cyber-attacks that could potentially disrupt our network operations or compromise proprietary data integrity, despite our ongoing investments in hardened security protocols."
  },
  {
   "category": "regulatory_legal",
   "severity": "medium",
   "affected_metric": "operating margin",
   "evidence_quote": "recent shifts in international spectrum allocation standards and stricter enforcement of regional antitrust laws may impose substantial compliance burdens or limit our ability to deploy critical hardware components across our key European markets."
  }
 ],
 "overall_risk_level": "high"
}

PREDICTION:
 {"risks": [{"category": "customer_concentration", "severity": "medium", "affected_metric": "revenue", "evidence_quote": "we derive approximately 42% of our total annual revenue from a single telecommunications service provider based in North America, and any decision by this counterparty to reduce its capital expenditure"}, {"category": "cybersecurity_operational", "severity": "medium", "affected_metric": "operating margin", "evidence_quote": "we face heightened exposure to sophisticated cyber-attacks that could potentially disrupt our network operations or compromise proprietary data integrity, despite our ongoing investments in hardened security protocols."}, {"category": "regulatory_legal", "severity": "high", "affected_metric": "net income", "evidence_quote": "recent shifts in international spectrum allocation standards and stricter enforcement of regional antitrust laws may impose substantial compliance burdens or limit our ability to deploy critical hardware components"}], "overall_risk_level": "high"}
====================================================================================================
ex_0042  auto=correct (categories match, quotes grounded, severities calibrated)

PASSAGE:
 At Halcyon Systems, we are committed to building a more resilient and sustainable global shipping fleet. During the fiscal year 2023, our capital investment program was largely focused on upgrading our vessel engines to utilize liquefied natural gas, aiming to reduce our overall carbon intensity by 15% compared to 2020 levels. However, we must remain vigilant regarding the shifting financial landscape that impacts our long-term stability. A significant portion of our corporate debt is structured with floating interest rates, which subjects our interest expense to volatility in global benchmark rates. Because we have chosen not to hedge the majority of our floating-rate exposure, any sustained upward movement in these benchmark rates will directly reduce our net income and cash flow available for future decarbonization investments. We believe that proactive debt management is essential as we navigate these macroeconomic challenges. Furthermore, we have successfully addressed the minor port congestion issues experienced in Southeast Asia during the first quarter; those logistical bottlenecks have been fully resolved through the implementation of our new automated terminal scheduling software, ensuring that our vessel turnaround times are now back to historical averages. Looking forward, our primary objective is to maintain a balance between our environmental commitments and the financial realities of our debt structure. We are continuously evaluating strategies to optimize our interest rate profile, ensuring that we remain competitive in a capital-intensive industry while adhering to our stringent sustainability goals and operational efficiency targets throughout the upcoming fiscal period.

REFERENCE:
 {
 "risks": [
  {
   "category": "fx_interest_rate",
   "severity": "high",
   "affected_metric": "net income",
   "evidence_quote": "A significant portion of our corporate debt is structured with floating interest rates, which subjects our interest expense to volatility in global benchmark rates. Because we have chosen not to hedge the majority of our floating-rate exposure, any sustained upward movement in these benchmark rates will directly reduce our net income"
  }
 ],
 "overall_risk_level": "high"
}

PREDICTION:
 {"risks": [{"category": "fx_interest_rate", "severity": "medium", "affected_metric": "net income", "evidence_quote": "A significant portion of our corporate debt is structured with floating interest rates, which subjects our interest expense to volatility in global benchmark rates."}], "overall_risk_level": "medium"}
====================================================================================================
ex_0171  auto=correct (categories match, quotes grounded, severities calibrated)

PASSAGE:
 Tidewell Technologies is pleased to report a strong finish to the fiscal year, marked by a record expansion of our container fleet and a notable improvement in our route optimization software. As we prepare for our initial public offering, our management team remains focused on long-term value creation and operational efficiency. Over the past twelve months, our team successfully integrated fifty new high-capacity vessels into our oceanic routes, which has directly contributed to a twelve percent increase in overall TEU capacity. We have achieved significant economies of scale by consolidating our maintenance schedules and leveraging our proprietary AI-driven logistics platform to minimize idling time at major ports. Furthermore, our recent expansion into the Southeast Asian market has proceeded ahead of schedule, with utilization rates for our new routes currently tracking above our initial internal projections. We have also finalized the renegotiation of several long-term service agreements with our primary logistics partners, which provides us with greater predictability regarding our port handling costs for the next three years. Our balance sheet remains robust, characterized by a conservative debt-to-equity ratio and a healthy cash position that provides the flexibility required to fund our planned fleet upgrades through the end of the decade. We believe our established position in major global shipping lanes, combined with our commitment to digital transformation, positions Tidewell Technologies to continue delivering superior performance for our shareholders. Our management team is dedicated to maintaining this momentum as we transition to a public company, ensuring that our infrastructure investments are aligned with global trade patterns and the evolving needs of our international shipping clientele.

REFERENCE:
 {
 "risks": [],
 "overall_risk_level": "none"
}

PREDICTION:
 {"risks": [], "overall_risk_level": "none"}
====================================================================================================
ex_0241  auto=correct (categories match, quotes grounded, severities calibrated)

PASSAGE:
 Good morning, everyone. At Redwater Corporation, we are navigating a complex landscape as we transition our manufacturing nodes to the next generation of 2nm architecture. We have successfully mitigated the minor production yield issue we encountered at our Dresden facility in Q1, which is now operating at full capacity. However, our current roadmap faces significant headwinds. We are struggling to stabilize the yield rates for our advanced extreme ultraviolet lithography processes, and if we fail to achieve commercial-grade reliability for these next-generation designs by the end of this fiscal year, our competitive position will be severely compromised as our proprietary architecture risks becoming obsolete against faster-moving industry standard alternatives. Additionally, the broader semiconductor market is showing signs of softening. We have observed a persistent contraction in global enterprise IT spending, particularly in the cloud infrastructure and data center sectors. This macroeconomic downturn has resulted in a marked decline in volume across our high-performance computing product lines. We anticipate that if these inflationary pressures continue to dampen capital expenditure among our primary hyperscale clients, our revenue targets for the remainder of the year will remain under significant downward pressure. We are closely monitoring these conditions and adjusting our inventory levels accordingly. Despite these challenges, our balance sheet remains strong, and we are committed to maintaining our long-term R&D investments to ensure we capture the next wave of industry growth when market sentiment eventually improves. Thank you for your continued support as we execute on these critical strategic objectives.

REFERENCE:
 {
 "risks": [
  {
   "category": "technology_ip",
   "severity": "high",
   "affected_metric": "market share",
   "evidence_quote": "if we fail to achieve commercial-grade reliability for these next-generation designs by the end of this fiscal year, our competitive position will be severely compromised as our proprietary architecture risks becoming obsolete"
  },
  {
   "category": "macroeconomic",
   "severity": "medium",
   "affected_metric": "revenue",
   "evidence_quote": "if these inflationary pressures continue to dampen capital expenditure among our primary hyperscale clients, our revenue targets for the remainder of the year will remain under significant downward pressure."
  }
 ],
 "overall_risk_level": "high"
}

PREDICTION:
 {"risks": [{"category": "technology_ip", "severity": "high", "affected_metric": "market share", "evidence_quote": "if we fail to achieve commercial-grade reliability for these next-generation designs by the end of this fiscal year, our competitive position will be severely compromised as our proprietary architecture risks becoming obsolete"}, {"category": "macroeconomic", "severity": "medium", "affected_metric": "revenue", "evidence_quote": "We anticipate that if these inflationary pressures continue to dampen capital expenditure among our primary hyperscale clients, our revenue targets for the remainder of the year will remain under significant downward pressure."}], "overall_risk_level": "high"}
====================================================================================================
ex_0312  auto=partially_correct (missing=['regulatory_legal'] extra=['esg_climate'])

PASSAGE:
 Looking ahead, our operational efficiency remains strong, though we face certain headwinds. We are currently navigating a sensitive labor negotiation at the Antofagasta site, where the departure of our chief metallurgist and three lead geologists has created a critical knowledge gap that threatens our 15% projected production increase for 2025. Furthermore, we are operating under an increasingly restrictive environmental framework in the region, as recent legislative amendments regarding water usage rights could force a 20% reduction in processing capacity if compliance measures aren't met by Q3. On the commercial front, 45% of our annual refined copper output is currently committed to a single industrial partner in East Asia, which exposes us to significant pricing volatility should their procurement strategy shift. We did encounter a brief supply disruption in early Q1 due to a rail blockage, but that issue was fully resolved in February with no lingering impact on our annual guidance.

REFERENCE:
 {
 "risks": [
  {
   "category": "key_personnel",
   "severity": "medium",
   "affected_metric": "operating margin",
   "evidence_quote": "the departure of our chief metallurgist and three lead geologists has created a critical knowledge gap that threatens our 15% projected production increase for 2025."
  },
  {
   "category": "regulatory_legal",
   "severity": "high",
   "affected_metric": "operating margin",
   "evidence_quote": "recent legislative amendments regarding water usage rights could force a 20% reduction in processing capacity if compliance measures aren't met by Q3."
  },
  {
   "category": "customer_concentration",
   "severity": "medium",
   "affected_metric": "revenue",
   "evidence_quote": "45% of our annual refined copper output is currently committed to a single industrial partner in East Asia, which exposes us to significant pricing volatility"
  }
 ],
 "overall_risk_level": "high"
}

PREDICTION:
 {"risks": [{"category": "key_personnel", "severity": "medium", "affected_metric": "operating margin", "evidence_quote": "the departure of our chief metallurgist and three lead geologists has created a critical knowledge gap that threatens our 15% projected production increase"}, {"category": "esg_climate", "severity": "medium", "affected_metric": "revenue", "evidence_quote": "recent legislative amendments regarding water usage rights could force a 20% reduction in processing capacity if compliance measures aren't met by Q3."}, {"category": "customer_concentration", "severity": "high", "affected_metric": "revenue", "evidence_quote": "45% of our annual refined copper output is currently committed to a single industrial partner in East Asia, which exposes us to significant pricing volatility"}], "overall_risk_level": "high"}
====================================================================================================
ex_0023  auto=correct (categories match, quotes grounded, severities calibrated)

PASSAGE:

In [ ]:
# Manual review: read every response printed above and label it yourself.
# Allowed: "correct", "partially_correct", "hallucinated" (success criteria in Task2_Data.ipynb).
# Self-contained so it can be re-run without the GPU session.
MANUAL_LABELS = {
    "ex_0317": "",
    "ex_0243": "",
    "ex_0042": "",
    "ex_0171": "",
    "ex_0241": "",
    "ex_0312": "",
    "ex_0023": "",
    "ex_0061": "",
    "ex_0273": "",
    "ex_0151": "",
    "ex_0154": "",
    "ex_0019": "",
    "ex_0099": "",
    "ex_0158": "",
    "ex_0324": "",
    "ex_0176": "",
    "ex_0185": "",
    "ex_0326": "",
    "ex_0131": "",
    "ex_0026": "",
    "ex_0294": "",
    "ex_0319": "",
    "ex_0095": "",
    "ex_0257": "",
    "ex_0246": "",
    "ex_0010": "",
    "ex_0147": "",
    "ex_0000": "",
    "ex_0228": "",
    "ex_0163": "",
    "ex_0130": "",
    "ex_0188": "",
}

import os, sys
while not os.path.exists("requirements.txt"):
    os.chdir("..")
sys.path.insert(0, os.getcwd())
from task2_genai.evaluation import hallucination_rate

ALLOWED = {"correct", "partially_correct", "hallucinated"}
filled = {k: v for k, v in MANUAL_LABELS.items() if v}
bad = {k: v for k, v in filled.items() if v not in ALLOWED}
assert not bad, f"invalid labels: {bad}"
assert len(filled) >= 10, f"label at least 10 responses (have {len(filled)})"
print("MANUAL REVIEW:", hallucination_rate(filled))

## Qualitative analysis

**Where fine-tuning helped.** The base model, with the same system prompt, mostly failed the output contract. Only
12.5% of its responses were valid schema JSON, and category recall was 0.14. It usually returned a partial list or
prose, so its high precision (0.82) only reflects how few categories it committed to. After QLoRA training, every
response was valid JSON (100%), and category F1 rose from 0.24 to 0.94. 90.6% of passages got exactly the right
category set, and 98.5% of evidence quotes were verbatim spans (up from 63.6%). ROUGE-L rose from 0.60 to 0.88 and
BERTScore F1 from 0.87 to 0.98. The LLM judge's "hallucinated" verdicts fell from 37.5% to 3.1%, and its
format-compliance score went from 3.1 to 5.0. For example, ex_0151 extracts three risks across cybersecurity, key
personnel and macroeconomic exposure, each with a verbatim quote and a calibrated severity. ex_0154 recovers all four
risks in a dense airline disclosure.

**Remaining failure modes and next steps.** Most errors sit on taxonomy boundaries rather than in fabricated content.
In ex_0312 and ex_0324, environmental regulation was labelled `esg_climate` instead of `regulatory_legal`. In ex_0000, a
single-manufacturer dependency was read as `customer_concentration` instead of `supply_chain`, and tariffs as
`fx_interest_rate` instead of `geopolitical`. Severity is the weakest dimension (accuracy 0.72); for example, ex_0188
rated a low supply-chain risk as high. The one grounding failure (ex_0154) is a one-word grammatical edit ("discounting"
became "discount") that breaks the verbatim rule. The RAG fallback fired on ex_0000 and fixed the tariff category but
dropped key_personnel, so retrieval alone is not a fix. Next steps:
- Add contrastive training pairs at the confused boundaries.
- Add explicit low/high severity anchors per category.
- Enforce quotes by snapping each one to the closest passage span or by constrained decoding.
- Validate on real 10-K passages to measure synthetic-to-real transfer.

## Bonus: RAG fallback (perplexity-gated ChromaDB retrieval)
Confidence = perplexity of the model's own generated tokens. The threshold is the 80th percentile on the validation set; above it (or on invalid JSON) the two most similar verified training extractions are retrieved from ChromaDB and the model is re-queried with them as calibration context.

In [12]:
from task2_genai.rag_fallback import answer_with_fallback, build_store, calibrate_threshold
from task2_genai.domain import label_response
from task2_genai.evaluation import passage_of
train, val = load_jsonl(DATA_DIR / "train.jsonl"), load_jsonl(DATA_DIR / "val.jsonl")
store = build_store(train)
ft_model, ft_tok = load_for_inference(FT_ID)
val_gens = generate(ft_model, ft_tok, [prompt_messages(r) for r in val])
THRESHOLD = calibrate_threshold([g["perplexity"] for g in val_gens])
print(f"perplexity threshold: {THRESHOLD:.4f}")

/root/.cache/chroma/onnx_models/all-MiniLM-L6-v2/onnx.tar.gz: 100%|██████████| 79.3M/79.3M [00:02<00:00, 31.6MiB/s]

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

perplexity threshold: 1.0229

In [13]:
ranked = sorted(zip(test, ft_gens), key=lambda x: -x[1]["perplexity"])
cases = [answer_with_fallback(ft_model, ft_tok, rec, store, THRESHOLD) for rec, _ in ranked[:3]]
for rec, case in zip([r for r, _ in ranked[:3]], cases):
    print("=" * 100, f"\n{case['id']} triggered={case['triggered']} reason={case['trigger_reason']}")
    print("BEFORE:", label_response(passage_of(rec), gold_of(rec), case["first"]["text"]), "\n", case["first"]["text"])
    if case["triggered"]:
        print("RETRIEVED:", case["retrieved"])
        print("AFTER: ", label_response(passage_of(rec), gold_of(rec), case["second"]["text"]), "\n", case["second"]["text"])

====================================================================================================
ex_0000 triggered=True reason=perplexity 1.027 > 1.023
BEFORE: ('partially_correct', "missing=['geopolitical', 'supply_chain'] extra=['customer_concentration', 'fx_interest_rate']")
 {"risks": [{"category": "customer_concentration", "severity": "medium", "affected_metric": "revenue", "evidence_quote": "our reliance on a single primary apparel manufacturer in Southeast Asia poses a significant risk to inventory availability should production cycles face further disruptions."}, {"category": "fx_interest_rate", "severity": "medium", "affected_metric": "operating margin", "evidence_quote": "rising trade tariffs between regional hubs could materially inflate our landed costs over the next two fiscal years."}, {"category": "key_personnel", "severity": "low", "affected_metric": "market share", "evidence_quote": "We are also monitoring the potential loss of our lead creative director, whose departure would likely destabilize our brand identity."}], "overall_risk_level": "medium"}
RETRIEVED: [{'id': 'ex_0142', 'distance': 0.3709}, {'id': 'ex_0232', 'distance': 0.4006}]
AFTER:  ('partially_correct', "missing=['key_personnel', 'supply_chain'] extra=['customer_concentration']")
 {"risks": [{"category": "customer_concentration", "severity": "high", "affected_metric": "inventory", "evidence_quote": "our reliance on a single primary apparel manufacturer in Southeast Asia poses a significant risk to inventory availability should production cycles face further disruptions."}, {"category": "geopolitical", "severity": "medium", "affected_metric": "operating margin", "evidence_quote": "rising trade tariffs between regional hubs could materially inflate our landed costs over the next two fiscal years."}], "overall_risk_level": "high"}
====================================================================================================
ex_0151 triggered=False reason=None
BEFORE: ('correct', 'categories match, quotes grounded, severities calibrated')
 {"risks": [{"category": "cybersecurity_operational", "severity": "high", "affected_metric": "operating margin", "evidence_quote": "any significant outage or sophisticated ransomware intrusion within this infrastructure could result in prolonged downtime, exposing us to stringent service level agreement penalties"}, {"category": "key_personnel", "severity": "medium", "affected_metric": "market share", "evidence_quote": "the loss of these key individuals, or our inability to attract elite software engineering talent amidst intensifying industry competition, would materially hinder our ability to innovate our proprietary data-analytics engine."}, {"category": "macroeconomic", "severity": "high", "affected_metric": "revenue", "evidence_quote": "An environment of sustained high interest rates or a contraction in general enterprise IT spending could lead these customers to aggressively reduce their seat licenses or defer renewals, thereby compressing our long-term operating margins"}], "overall_risk_level": "high"}
====================================================================================================
ex_0243 triggered=False reason=None
BEFORE: ('correct', 'categories match, quotes grounded, severities calibrated')
 {"risks": [{"category": "customer_concentration", "severity": "medium", "affected_metric": "revenue", "evidence_quote": "we derive approximately 42% of our total annual revenue from a single telecommunications service provider based in North America, and any decision by this counterparty to reduce its capital expenditure"}, {"category": "cybersecurity_operational", "severity": "medium", "affected_metric": "operating margin", "evidence_quote": "we face heightened exposure to sophisticated cyber-attacks that could potentially disrupt our network operations or compromise proprietary data integrity, despite our ongoing investments in hardened security protocols."}, {"category": "regulatory_legal", "severity": "high", "affected_metric": "net income", "evidence_quote": "recent shifts in international spectrum allocation standards and stricter enforcement of regional antitrust laws may impose substantial compliance burdens or limit our ability to deploy critical hardware components"}], "overall_risk_level": "high"}